### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by Magnitus-** [regexps/regex-email#2]
In the usage section, you have the following:

var regex = require('regex-utc-date');

Shouldn't it be?:

var regex = require('regex-email ');

**Comment by kevva** [comment]
Where?

**Comment by Magnitus-** [comment]
There:

https://www.npmjs.com/package/regex-email

EDIT:

Actually, nvm. Just noticed the publisher of the npm package seems to be a different guy and the documentation in the Github repo is correct.

**Comment by kevva** [comment]
It's because the package hasn't been published since the README was updated.

**Comment by Magnitus-** [comment]
Ok, I'll send an email to the maintainer of the npm repo.

Thanks for a ridiculously quick feedback.

**Comment by kevva** [comment]
Just ping him here. @yoshuawuyts, could you do a patch relase?

**Comment by Magnitus-** [comment]
> Just ping him here, @tunnckoCore

K, I'll contact him there.

EDIT: Actually, sent him an email at his posted email address.

> could you do a patch relase?

Do you mean a new npm repo with the right doc? Sounds wasteful if the original publisher of the npm repo can simply patch his release.

**Comment by kevva** [comment]
@Magnitus-, that's what I meant :).

**Comment by Magnitus-** [comment]
Ok, I'll give him a reasonable amount of time to update and if that hasn't happened by then, then I'll patch.

**Comment by kevva** [comment]
@Magnitus-, you don't need to. Just wait.

**Comment by yoshuawuyts** [comment]
Released as `1.0.2`. Didn't receive an email by the way :cry:

**Comment by Magnitus-** [comment]
Sorry, the mailer-daemon gave up ;)
